# Generated by Django 3.2.9 on 2021-11-18 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title of address')),
                ('country', models.CharField(max_length=20, verbose_name='country')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('zone', models.CharField(max_length=20, verbose_name='zone')),
                ('number', models.PositiveIntegerField(verbose_name='number')),
                ('zip_code', models.PositiveIntegerField(verbose_name='zip code of address')),
                ('is_customer', models.BooleanField(verbose_name='is it customer address?s')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
